## GIBMS7015 Neural Network Assignment 1  (MATLAB/Octave version)##
by HSING Chih-Chia(R08454015)  
2020.Apr.02

***
#### Question 1: ####

In [0]:
b = [3;1;2];
C = [3,2,1;1,2,0;3,4,1];

a1 = C*b + 5*[1;1;1]

a1 =

   18
   10
   20



***
#### Question 2 ####

In [0]:
d = [4;2;1];

a2 = 3*d + C*b + 5*1

a2 =

   30
   16
   23



***
#### Question 3 ####
a) C/2 is computable. Matrix operation with scalar value is mathematically possible.

In [0]:
C/2

ans =

   1.50000   1.00000   0.50000
   0.50000   1.00000   0.00000
   1.50000   2.00000   0.50000



b) C+d is mathematically not computable, yet since 2016a MATLAB has made it possible with implicit expansion so it works now.

In [0]:
C+d

ans =

   7   6   5
   3   4   2
   4   5   2



c) b*d' is computable, since the column of matrix b matches that of the row of matrix d'.

In [0]:
b*d'

ans =

   12    6    3
    4    2    1
    8    4    2



d) b*d is not computable, since the column of matrix b does not match that of the row of matrix d'

In [0]:
b*d

error: operator *: nonconformant arguments (op1 is 3x1, op2 is 3x1)


e) C*(b+d) is computable, since the column of matrix C matches that of the row of matrix b+d

In [0]:
C*(b+d)

ans =

   30
   13
   36



***
#### Question 4 ####

In [0]:
E = [1,0,0;0,2,0;0,0,1];
F = [3,0,0;0,4,0;0,0,1];

G = E*F
H = F*E

G =

   3   0   0
   0   8   0
   0   0   1

H =

   3   0   0
   0   8   0
   0   0   1



G is equal to H, this only happens beacause E and F are both diagnal matrices.

***
#### Question 5 ####

In [0]:
v = [3,1,0];
u = zeros(length(v),1);
for i=1:3
    u(i) = 1/(1+exp(-v(i)));
end

u

u =

   0.95257
   0.73106
   0.50000

