## GIBMS7015 Neural Network Assignment 1  (R version)##
by HSING Chih-Chia (R08454015)  
2020.Apr.02

***
#### Question 1 ####

In [0]:
b <- c(3,1,2)
dim(b) <- c(3,1)

C <- c(3,1,3,2,2,4,1,0,1)
dim(C) <- c(3,3)

onemat <- c(1,1,1)
dim(onemat) <- c(3,1)

In [0]:
a <- C%*%b + 5*onemat
a

[,1]
[1,] 18  
[2,] 10  
[3,] 20

***
#### Question 2 ####

In [0]:
d <- c(4,2,1)
dim(d) <- c(3,1)

In [0]:
a <- 3*d + C%*%b + 5*onemat
a

[,1]
[1,] 30  
[2,] 16  
[3,] 23

***
#### Question 3 ####
Q3a) is computable

In [0]:
C/2

[,1] [,2] [,3]
[1,] 1.5  1    0.5 
[2,] 0.5  1    0.0 
[3,] 1.5  2    0.5

b) is not computable 

In [0]:
C+d

ERROR: Error in C + d:  適切な配列ではありません 


c) is computable

In [0]:
b%*%t(d)

[,1] [,2] [,3]
[1,] 12   6    3   
[2,]  4   2    1   
[3,]  8   4    2

d) is not computable

In [0]:
b%*%d

ERROR: Error in b %*% d:  適切な引数ではありません 


e) is computable

In [0]:
C%*%(b+d)

[,1]
[1,] 30  
[2,] 13  
[3,] 36

***
#### Question 4 ####

In [0]:
E <- c(1,0,0,0,2,0,0,0,1)
dim(E) <- c(3,3)

F <- c(3,0,0,0,4,0,0,0,1)
dim(F) <- c(3,3)

In [0]:
G <- E %*% F
G

H <- F %*% E
H

[,1] [,2] [,3]
[1,] 3    0    0   
[2,] 0    8    0   
[3,] 0    0    1

[,1] [,2] [,3]
[1,] 3    0    0   
[2,] 0    8    0   
[3,] 0    0    1

G is equal to H, this only works when E and F are both diagnal matrices.

In [0]:
identical(G,H)

[1] TRUE

#### Question 5 ####

In [0]:
v <- c(3,1,0)
dim(v) <- c(3,1)

u <- 1/(1+exp(-v))

In [0]:
u

[,1]     
[1,] 0.9525741
[2,] 0.7310586
[3,] 0.5000000