## GIBMS7015 Neural Network Assignment 1 (Python version)## 
by HSING Chih-Chia(R08454015)  
2020.Apr.02

***
#### Question 1 ####

In [1]:
import numpy as np

In [2]:
b=np.array([[3],[1],[2]])
C=np.array([[3,2,1],[1,2,0],[3,4,1]])

onemat=np.array([[1],[1],[1]])

In [3]:
a=np.dot(C,b)+5*onemat
print(a)

[[18]
 [10]
 [20]]


***
#### Question 2 ####

In [4]:
d=np.array([[4],[2],[1]]);
a=3*d+np.dot(C,b)+5*onemat
print(a)

[[30]
 [16]
 [23]]


***
#### Question 3 ####

Q3a) is computable

In [5]:
C/2

array([[1.5, 1. , 0.5],
       [0.5, 1. , 0. ],
       [1.5, 2. , 0.5]])

Q3b) is mathematically not computable. However, Numpy has this 'broadcasting' feature that makes summation of C and d possible

In [6]:
np.add(C,d)

array([[7, 6, 5],
       [3, 4, 2],
       [4, 5, 2]])

Q3c) is computable

In [7]:
np.dot(b,d.T)

array([[12,  6,  3],
       [ 4,  2,  1],
       [ 8,  4,  2]])

Q3d) is not computable because the dimensions don't match

In [8]:
np.dot(b,d)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

Q3e) is computable 

In [9]:
np.dot(C,b+d)

array([[30],
       [13],
       [36]])

***
#### Question 4 ####

In [10]:
E = np.array([[1,0,0],[0,2,0],[0,0,1]])
F = np.array([[3,0,0],[0,4,0],[0,0,1]])

In [11]:
G = np.dot(E,F)
H = np.dot(F,E)
print(G)

[[3 0 0]
 [0 8 0]
 [0 0 1]]


In [12]:
np.array_equal(G,H)

True

***
#### Question 5 ####

In [13]:
v = np.array([[3],[1],[0]])

In [14]:
u = 1/(1+np.exp(-v))
print(u)

[[0.95257413]
 [0.73105858]
 [0.5       ]]
